/**
 * Regression tests for the five defects fixed in v0.3.7.
 *
 * Each test names the bug it locks down and asserts the specific wrong
 * behaviour is gone — not merely that the happy path still works. The
 * failure modes were all silent or misleading in production, which is
 * exactly the class of bug that reappears without a test pinning it.
 *
 * The Postgres-facing halves (identity INSERT semantics, TRUNCATE without
 * CASCADE) were verified against a live PostgreSQL 16.13 instance during
 * the fix; what is asserted here is the CLI-side logic that decides what
 * SQL gets built.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import type { Column, Table } from "./introspect.js";
import { buildRowSchema } from "./schema.js";
import { validateTable } from "./validate.js";
import { planRun } from "./runner.js";
import { synthesizePkRows, createSimulatedProvider } from "./simulate.js";
import {
  classifyError,
  telemetryEnabled,
  configureTelemetry,
  isTelemetryEnabled,
  reportRun,
} from "./telemetry.js";
import { INTROSPECT_SQL } from "./introspect.js";
import { createAnthropicProvider } from "./providers/anthropic.js";
import { createOpenAiProvider } from "./providers/openai.js";
import type { Provider } from "./providers/types.js";

function col(name: string, udt: string, opts: Partial<Column> = {}): Column {
  return {
    name,
    dataType: udt,
    udtName: udt,
    isNullable: false,
    hasDefault: false,
    defaultExpr: null,
    charMaxLength: null,
    numericPrecision: null,
    numericScale: null,
    isGenerated: false,
    isIdentity: false,
    identityGeneration: null,
    ...opts,
  };
}

function tbl(name: string, columns: Column[], extra: Partial<Table> = {}): Table {
  return {
    schema: "public",
    name,
    columns,
    primaryKey: extra.primaryKey ?? [],
    foreignKeys: extra.foreignKeys ?? [],
    uniqueColumns: extra.uniqueColumns ?? new Set<string>(),
  };
}

/* ------------------------------------------------------------------ *
 * Bug 1 — IDENTITY columns were handed to the model.
 *
 * Postgres reports an identity column with column_default = NULL and
 * is_generated = 'NEVER', so neither hasDefault nor isGenerated caught it.
 * Verified on PG 16.13:
 *   - GENERATED ALWAYS rejects an explicit value outright
 *     ("cannot insert a non-DEFAULT value into column"), aborting the run's
 *     single transaction.
 *   - GENERATED BY DEFAULT accepts it but leaves the sequence at its old
 *     value, so the application's next insert collides with a seeded row.
 * ------------------------------------------------------------------ */
describe("regression: identity columns are left to the database", () => {
  const identityTable = tbl(
    "users",
    [
      col("id", "int4", { isIdentity: true, identityGeneration: "ALWAYS" }),
      col("legacy_id", "int4", { isIdentity: true, identityGeneration: "BY DEFAULT" }),
      col("email", "text"),
    ],
    { primaryKey: ["id"] },
  );

  it("excludes both identity variants from the model schema", () => {
    const built = buildRowSchema(identityTable, 3);
    const names = built.modelColumns.map((c) => c.name);
    expect(names).toEqual(["email"]);
    expect(names).not.toContain("id");
    expect(names).not.toContain("legacy_id");
  });

  it("excludes identity columns from the INSERT column list", () => {
    // If they reach insertColumns the writer names them in the INSERT and
    // Postgres either errors (ALWAYS) or skips the sequence (BY DEFAULT).
    expect(buildRowSchema(identityTable, 1).insertColumns).toEqual(["email"]);
  });

  it("does not report NOT NULL findings for identity columns", () => {
    // The runner omits them, so the row has no key for them. Before the
    // fix the validator flagged that absence as a NOT NULL violation and
    // every dry-run on an identity schema exited non-zero.
    const findings = validateTable(identityTable, {
      rows: [{ email: "ada@example.test" }],
      pkPool: new Map(),
    });
    expect(findings).toEqual([]);
  });

  it("still asks the model for an ordinary NOT NULL integer column", () => {
    // Guards against over-correcting into "skip every integer PK-ish column".
    const plain = tbl("t", [col("id", "int4"), col("name", "text")], { primaryKey: ["id"] });
    expect(buildRowSchema(plain, 1).modelColumns.map((c) => c.name)).toEqual(["id", "name"]);
  });
});

/* ------------------------------------------------------------------ *
 * Bug 2 — a FK pointing at a non-PK column silently became NULL.
 *
 * insertRows only ever RETURNed primary-key columns, so the pooled parent
 * row had no key for a FK targeting a UNIQUE non-PK column. Reading it
 * gave undefined, the writer's serialize() turned undefined into null, and
 * a nullable child column inserted unlinked with no error anywhere.
 * ------------------------------------------------------------------ */
describe("regression: FK targeting a non-PK column", () => {
  it("carries the referenced non-PK column into the dry-run pool", () => {
    const users = tbl("users", [col("id", "int4", { isIdentity: true }), col("email", "text")], {
      primaryKey: ["id"],
      uniqueColumns: new Set(["email"]),
    });
    // `orders.user_email -> users.email` — a real pattern, and not a PK.
    const pool = synthesizePkRows(
      users,
      [{ email: "ada@example.test" }, { email: "grace@example.test" }],
      ["email"],
    );

    expect(pool).toHaveLength(2);
    for (const row of pool) {
      expect(row).toHaveProperty("id");
      expect(row).toHaveProperty("email");
      // The real generated value is carried through, not re-invented, so
      // the validator compares against what a real run would have written.
      expect(row.email).toMatch(/@example\.test$/);
      expect(row.email).not.toBeUndefined();
    }
    expect(pool[0]!.email).toBe("ada@example.test");
  });

  it("synthesizes a referenced column the database would have defaulted", () => {
    // A referenced column with a DB default never appears in the model's
    // output, so there is nothing to carry through — it must still land in
    // the pool rather than being absent.
    const parent = tbl(
      "tenants",
      [col("id", "int4", { isIdentity: true }), col("slug", "uuid", { hasDefault: true })],
      { primaryKey: ["id"], uniqueColumns: new Set(["slug"]) },
    );
    const pool = synthesizePkRows(parent, [{}, {}], ["slug"]);
    expect(pool).toHaveLength(2);
    expect(typeof pool[0]!.slug).toBe("string");
    expect(pool[0]!.slug).not.toBe(pool[1]!.slug);
  });

  it("keeps returning plain PK rows when nothing references a non-PK column", () => {
    const t = tbl("t", [col("id", "int4", { isIdentity: true })], { primaryKey: ["id"] });
    const pool = synthesizePkRows(t, [{}, {}], []);
    expect(pool).toEqual([{ id: 1 }, { id: 2 }]);
  });
});

/* ------------------------------------------------------------------ *
 * Bug 3 — the dry-run estimate and the live meter used different prices.
 *
 * planRun hardcoded gpt-4o-mini's $0.15/$0.60 regardless of --provider, so
 * an Anthropic run was estimated at OpenAI's cheapest rate and then metered
 * at Anthropic's. On top of that the Anthropic price table was empty and
 * its fallback ($3/$15) was exactly 3x the real rate for the default model
 * (claude-haiku-4-5 at $1/$5), so --max-cost aborted runs nowhere near the
 * cap.
 * ------------------------------------------------------------------ */
describe("regression: one price table drives both cost numbers", () => {
  const anthropic = createAnthropicProvider({ apiKey: "x", model: "claude-haiku-4-5" });
  const openai = createOpenAiProvider({ apiKey: "x", model: "gpt-4o-mini" });

  it("prices the default Anthropic model at its real rate", () => {
    expect(anthropic.rates).toEqual({ inputPerMTok: 1, outputPerMTok: 5 });
  });

  it("resolves a dated model id to its family", () => {
    const dated = createAnthropicProvider({ apiKey: "x", model: "claude-haiku-4-5-20251001" });
    expect(dated.rates).toEqual({ inputPerMTok: 1, outputPerMTok: 5 });
  });

  it("prefers the longest matching prefix", () => {
    // 'gpt-4o-mini' must not be shadowed by 'gpt-4o' whatever the key order.
    expect(openai.rates).toEqual({ inputPerMTok: 0.15, outputPerMTok: 0.6 });
    expect(createOpenAiProvider({ apiKey: "x", model: "gpt-4o" }).rates).toEqual({
      inputPerMTok: 2.5,
      outputPerMTok: 10,
    });
  });

  it("falls back pessimistically for an unpriced model", () => {
    // A guardrail that under-bills is worse than one that over-bills: the
    // former overshoots --max-cost silently. Both fallbacks must be >= every
    // rate in their own table.
    const unknownAnthropic = createAnthropicProvider({ apiKey: "x", model: "claude-future-9" });
    const unknownOpenai = createOpenAiProvider({ apiKey: "x", model: "o9-preview" });
    expect(unknownAnthropic.rates.inputPerMTok).toBeGreaterThanOrEqual(10);
    expect(unknownAnthropic.rates.outputPerMTok).toBeGreaterThanOrEqual(50);
    expect(unknownOpenai.rates.inputPerMTok).toBeGreaterThanOrEqual(2.5);
    expect(unknownOpenai.rates.outputPerMTok).toBeGreaterThanOrEqual(10);
  });

  it("estimates with the selected provider rather than a hardcoded OpenAI rate", () => {
    const tables = [tbl("t", [col("a", "text"), col("b", "text")])];
    const opts = (provider: Provider) => ({
      rowsPerTable: 10,
      batchSize: 25,
      profile: "saas" as const,
      provider,
      maxCostUsd: 1,
      dryRun: true,
    });

    const viaAnthropic = planRun(tables, opts(anthropic))[0]!.estimatedCostUsd;
    const viaOpenai = planRun(tables, opts(openai))[0]!.estimatedCostUsd;

    // 2 cols x 10 rows = 20 cells -> 1600 input + 800 output tokens.
    expect(viaAnthropic).toBeCloseTo((1600 / 1e6) * 1 + (800 / 1e6) * 5, 10);
    expect(viaOpenai).toBeCloseTo((1600 / 1e6) * 0.15 + (800 / 1e6) * 0.6, 10);
    expect(viaAnthropic).not.toBeCloseTo(viaOpenai, 10);
  });

  it("estimates zero only for the simulated provider", () => {
    const sim = createSimulatedProvider();
    expect(sim.rates).toEqual({ inputPerMTok: 0, outputPerMTok: 0 });
  });
});

/* ------------------------------------------------------------------ *
 * Bug 4 — run telemetry contradicted the published privacy promise.
 *
 * The README promises "no table or column names, no row data". The payload
 * carried every table name, the schema name, and raw error text. Postgres
 * unique-violation messages embed the offending value verbatim, so the
 * third one leaked actual customer rows.
 * ------------------------------------------------------------------ */
describe("regression: telemetry error classification leaks nothing", () => {
  it("reduces a Postgres unique violation to its SQLSTATE", () => {
    const pgErr = Object.assign(
      new Error(
        'duplicate key value violates unique constraint "users_email_key"\n' +
          "Key (email)=(ada@example.com) already exists.",
      ),
      { code: "23505" },
    );
    const cls = classifyError(pgErr);
    expect(cls).toBe("pg_23505");
    expect(cls).not.toContain("ada@example.com");
    expect(cls).not.toContain("users");
    expect(cls).not.toContain("email");
  });

  it("reduces a provider failure to its HTTP status", () => {
    expect(classifyError(new Error("Anthropic 429: rate limited"))).toBe("provider_http_429");
    expect(classifyError(new Error('OpenAI 400: {"error":{"message":"..."}}'))).toBe(
      "provider_http_400",
    );
  });

  it("recognises the failures satus raises itself", () => {
    expect(classifyError(new Error("Cost budget exceeded ($2.00 > $1)"))).toBe("budget_exceeded");
    expect(
      classifyError(new Error("No parent rows available for orders.user_id -> users.id.")),
    ).toBe("no_parent_rows");
    expect(classifyError(new Error("Cannot resolve orders.user_email -> users.email: ..."))).toBe(
      "fk_unresolvable",
    );
    expect(classifyError(new Error("--truncate cannot run: ..."))).toBe("truncate_blocked");
  });

  it("returns a constant rather than a truncated message for anything unknown", () => {
    // The dangerous alternative is slicing the message: a truncated
    // Postgres error is precisely where a row value would survive.
    const leaky = new Error("some novel failure mentioning secret_table.customer_ssn");
    const cls = classifyError(leaky);
    expect(cls).toBe("unknown");
    expect(cls).not.toContain("secret_table");
    expect(cls).not.toContain("customer_ssn");
  });

  it("never emits anything outside a safe character set", () => {
    // The ingest route validates /^[a-zA-Z0-9_]+$/; a class that fails it
    // would be silently dropped as an invalid payload.
    const samples = [
      Object.assign(new Error("x"), { code: "23503" }),
      new Error("Anthropic 404:"),
      new Error("Failed to parse model JSON: Unexpected token"),
      new Error("OpenAI returned no content"),
      new Error("Anthropic returned no 'emit_rows' tool_use block (stop_reason=max_tokens)."),
      new Error("anything at all"),
      null,
      undefined,
    ];
    for (const s of samples) {
      expect(classifyError(s)).toMatch(/^[a-zA-Z0-9_]+$/);
    }
  });
});

/* ------------------------------------------------------------------ *
 * Bug 6 — primary keys and unique columns vanished for read-only roles.
 *
 * v_fks read pg_catalog precisely because information_schema is
 * privilege-filtered, but v_pks and v_uniques still went through
 * information_schema.table_constraints, whose predicate is:
 *
 *   pg_has_role(relowner, 'USAGE')
 *   OR has_table_privilege(INSERT, UPDATE, DELETE, TRUNCATE,
 *                          REFERENCES, TRIGGER)
 *   OR has_any_column_privilege(INSERT, UPDATE, REFERENCES)
 *
 * SELECT is absent from that list. Verified on PostgreSQL 16.13: running
 * the shipped query as a role holding only SELECT returned 3 tables and
 * 10 columns but 0 primary keys and 0 uniques, while pg_catalog returned
 * all of them. Nothing raised — the run would simply have proceeded with
 * an empty PK for every table, silently disabling updateBrokenEdge and
 * the unique-column validator.
 *
 * This is a shape assertion rather than a live-DB test: the defect was
 * which catalog the SQL reads, so that is what gets pinned.
 * ------------------------------------------------------------------ */
describe("regression: constraint introspection does not use information_schema", () => {
  const ctes = ["v_pks", "v_uniques", "v_fks_raw"];

  function bodyOf(cte: string): string {
    const start = INTROSPECT_SQL.indexOf(`${cte} as (`);
    expect(start, `${cte} should exist in INTROSPECT_SQL`).toBeGreaterThan(-1);
    // Walk to the matching close paren so we read only this CTE.
    let depth = 0;
    let i = INTROSPECT_SQL.indexOf("(", start);
    const from = i;
    for (; i < INTROSPECT_SQL.length; i++) {
      if (INTROSPECT_SQL[i] === "(") depth++;
      else if (INTROSPECT_SQL[i] === ")") {
        depth--;
        if (depth === 0) break;
      }
    }
    // Strip `--` comments: these CTEs explain in prose which catalog they
    // avoid, and the assertion below is about the SQL, not the commentary.
    return INTROSPECT_SQL.slice(from, i)
      .split("\n")
      .map((line) => line.replace(/--.*$/, ""))
      .join("\n");
  }

  for (const cte of ctes) {
    it(`${cte} reads pg_catalog, not information_schema`, () => {
      const body = bodyOf(cte);
      expect(body).not.toContain("information_schema");
      expect(body).toContain("pg_constraint");
    });
  }

  it("still reads columns from information_schema.columns", () => {
    // columns is filtered by *column* privilege, which does accept SELECT,
    // so it is correct there and the fix should not have touched it.
    expect(bodyOf("v_columns")).toContain("information_schema.columns");
  });

  it("only single-column unique constraints are reported", () => {
    // Multi-column uniques are an explicit v0.x limitation; the pg_catalog
    // rewrite must not silently start reporting them as single-column.
    expect(bodyOf("v_uniques")).toContain("cardinality(con.conkey) = 1");
  });
});

/* ------------------------------------------------------------------ *
 * Bug 7 — run telemetry was on unconditionally.
 *
 * satus.sh/security has said "Telemetry. Off by default" since the page
 * went up. `reportRun` was called at the end of every `satus generate`
 * with no config key, env var, or flag able to stop it. The payload was
 * already minimal and the two sensitive extras (schema fingerprint, argv
 * shape) were already gated behind `share_failure_fingerprints`, so
 * nothing identifying ever left a user's machine — but the published
 * sentence described behaviour the CLI did not have.
 *
 * v0.3.11 makes the run record opt-in. These tests pin the precedence
 * rules, and especially the default, because the failure mode is silent:
 * a regression here sends data while a page promises it does not.
 * ------------------------------------------------------------------ */
describe("regression: run telemetry is opt-in", () => {
  const saved = {
    DO_NOT_TRACK: process.env.DO_NOT_TRACK,
    SATUS_TELEMETRY: process.env.SATUS_TELEMETRY,
  };
  function env(vars: Record<string, string | undefined>) {
    for (const k of ["DO_NOT_TRACK", "SATUS_TELEMETRY"]) delete process.env[k];
    for (const [k, v] of Object.entries(vars)) if (v !== undefined) process.env[k] = v;
  }
  afterEach(() => {
    for (const [k, v] of Object.entries(saved)) {
      if (v === undefined) delete process.env[k];
      else process.env[k] = v;
    }
  });

  it("is off when nothing is configured", () => {
    env({});
    expect(telemetryEnabled(undefined)).toBe(false);
    expect(telemetryEnabled(false)).toBe(false);
  });

  it("is on only when the config key is explicitly true", () => {
    env({});
    expect(telemetryEnabled(true)).toBe(true);
  });

  it("lets SATUS_TELEMETRY override the config in both directions", () => {
    env({ SATUS_TELEMETRY: "1" });
    expect(telemetryEnabled(false)).toBe(true);
    env({ SATUS_TELEMETRY: "0" });
    expect(telemetryEnabled(true)).toBe(false);
  });

  it("accepts the usual truthy spellings and treats blank as unset", () => {
    for (const on of ["1", "true", "YES", "On"]) {
      env({ SATUS_TELEMETRY: on });
      expect(telemetryEnabled(false), `${on} should enable`).toBe(true);
    }
    // Blank must fall through to config rather than reading as "off",
    // otherwise `SATUS_TELEMETRY= satus generate` silently disables an
    // opt-in the user actually made.
    env({ SATUS_TELEMETRY: "  " });
    expect(telemetryEnabled(true)).toBe(true);
  });

  it("lets DO_NOT_TRACK win over every other signal", () => {
    env({ DO_NOT_TRACK: "1", SATUS_TELEMETRY: "1" });
    expect(telemetryEnabled(true)).toBe(false);
  });

  it("starts disabled in a freshly loaded module", async () => {
    // The latch must be off at import time, before anything configures it.
    // Asserting this needs a pristine module: every other test in this file
    // has already called configureTelemetry, so the live binding no longer
    // reflects the initial value. resetModules + dynamic import gives a new
    // instance whose `enabled` is whatever the source initialises it to.
    env({});
    vi.resetModules();
    const fresh = await import("./telemetry.js");
    expect(fresh.isTelemetryEnabled()).toBe(false);
  });

  it("sends nothing until configureTelemetry has run", async () => {
    // Fail closed: a code path that never configures must not report.
    // reportRun swallows everything, so assert on the latch and on fetch
    // never being reached.
    env({});
    const calls: unknown[] = [];
    const originalFetch = globalThis.fetch;
    globalThis.fetch = (...args: unknown[]) => {
      calls.push(args);
      return Promise.resolve(new Response("{}")) as never;
    };
    try {
      configureTelemetry(false);
      expect(isTelemetryEnabled()).toBe(false);
      await reportRun("run-id", { status: "success" });
      expect(calls).toHaveLength(0);

      configureTelemetry(true);
      expect(isTelemetryEnabled()).toBe(true);
      await reportRun("run-id", { status: "success" });
      expect(calls).toHaveLength(1);
    } finally {
      globalThis.fetch = originalFetch;
      configureTelemetry(false);
    }
  });
});
