/**
 * Regression tests for the five defects fixed in v0.3.7.
 *
 * Each test names the bug it locks down and asserts the specific wrong
 * behaviour is gone — not merely that the happy path still works. The
 * failure modes were all silent or misleading in production, which is
 * exactly the class of bug that reappears without a test pinning it.
 *
 * The Postgres-facing halves (identity INSERT semantics, TRUNCATE without
 * CASCADE) were verified against a live PostgreSQL 16.13 instance during
 * the fix; what is asserted here is the CLI-side logic that decides what
 * SQL gets built.
 */
import { describe, it, expect } from 'vitest'
import type { Column, Table } from './introspect.js'
import { buildRowSchema } from './schema.js'
import { validateTable } from './validate.js'
import { planRun } from './runner.js'
import { synthesizePkRows, createSimulatedProvider } from './simulate.js'
import { classifyError } from './telemetry.js'
import { createAnthropicProvider } from './providers/anthropic.js'
import { createOpenAiProvider } from './providers/openai.js'
import type { Provider } from './providers/types.js'

function col(name: string, udt: string, opts: Partial<Column> = {}): Column {
  return {
    name,
    dataType: udt,
    udtName: udt,
    isNullable: false,
    hasDefault: false,
    defaultExpr: null,
    charMaxLength: null,
    numericPrecision: null,
    numericScale: null,
    isGenerated: false,
    isIdentity: false,
    identityGeneration: null,
    ...opts,
  }
}

function tbl(name: string, columns: Column[], extra: Partial<Table> = {}): Table {
  return {
    schema: 'public',
    name,
    columns,
    primaryKey: extra.primaryKey ?? [],
    foreignKeys: extra.foreignKeys ?? [],
    uniqueColumns: extra.uniqueColumns ?? new Set<string>(),
  }
}

/* ------------------------------------------------------------------ *
 * Bug 1 — IDENTITY columns were handed to the model.
 *
 * Postgres reports an identity column with column_default = NULL and
 * is_generated = 'NEVER', so neither hasDefault nor isGenerated caught it.
 * Verified on PG 16.13:
 *   - GENERATED ALWAYS rejects an explicit value outright
 *     ("cannot insert a non-DEFAULT value into column"), aborting the run's
 *     single transaction.
 *   - GENERATED BY DEFAULT accepts it but leaves the sequence at its old
 *     value, so the application's next insert collides with a seeded row.
 * ------------------------------------------------------------------ */
describe('regression: identity columns are left to the database', () => {
  const identityTable = tbl(
    'users',
    [
      col('id', 'int4', { isIdentity: true, identityGeneration: 'ALWAYS' }),
      col('legacy_id', 'int4', { isIdentity: true, identityGeneration: 'BY DEFAULT' }),
      col('email', 'text'),
    ],
    { primaryKey: ['id'] },
  )

  it('excludes both identity variants from the model schema', () => {
    const built = buildRowSchema(identityTable, 3)
    const names = built.modelColumns.map((c) => c.name)
    expect(names).toEqual(['email'])
    expect(names).not.toContain('id')
    expect(names).not.toContain('legacy_id')
  })

  it('excludes identity columns from the INSERT column list', () => {
    // If they reach insertColumns the writer names them in the INSERT and
    // Postgres either errors (ALWAYS) or skips the sequence (BY DEFAULT).
    expect(buildRowSchema(identityTable, 1).insertColumns).toEqual(['email'])
  })

  it('does not report NOT NULL findings for identity columns', () => {
    // The runner omits them, so the row has no key for them. Before the
    // fix the validator flagged that absence as a NOT NULL violation and
    // every dry-run on an identity schema exited non-zero.
    const findings = validateTable(identityTable, {
      rows: [{ email: 'ada@example.test' }],
      pkPool: new Map(),
    })
    expect(findings).toEqual([])
  })

  it('still asks the model for an ordinary NOT NULL integer column', () => {
    // Guards against over-correcting into "skip every integer PK-ish column".
    const plain = tbl('t', [col('id', 'int4'), col('name', 'text')], { primaryKey: ['id'] })
    expect(buildRowSchema(plain, 1).modelColumns.map((c) => c.name)).toEqual(['id', 'name'])
  })
})

/* ------------------------------------------------------------------ *
 * Bug 2 — a FK pointing at a non-PK column silently became NULL.
 *
 * insertRows only ever RETURNed primary-key columns, so the pooled parent
 * row had no key for a FK targeting a UNIQUE non-PK column. Reading it
 * gave undefined, the writer's serialize() turned undefined into null, and
 * a nullable child column inserted unlinked with no error anywhere.
 * ------------------------------------------------------------------ */
describe('regression: FK targeting a non-PK column', () => {
  it('carries the referenced non-PK column into the dry-run pool', () => {
    const users = tbl(
      'users',
      [col('id', 'int4', { isIdentity: true }), col('email', 'text')],
      { primaryKey: ['id'], uniqueColumns: new Set(['email']) },
    )
    // `orders.user_email -> users.email` — a real pattern, and not a PK.
    const pool = synthesizePkRows(
      users,
      [{ email: 'ada@example.test' }, { email: 'grace@example.test' }],
      ['email'],
    )

    expect(pool).toHaveLength(2)
    for (const row of pool) {
      expect(row).toHaveProperty('id')
      expect(row).toHaveProperty('email')
      // The real generated value is carried through, not re-invented, so
      // the validator compares against what a real run would have written.
      expect(row.email).toMatch(/@example\.test$/)
      expect(row.email).not.toBeUndefined()
    }
    expect(pool[0]!.email).toBe('ada@example.test')
  })

  it('synthesizes a referenced column the database would have defaulted', () => {
    // A referenced column with a DB default never appears in the model's
    // output, so there is nothing to carry through — it must still land in
    // the pool rather than being absent.
    const parent = tbl(
      'tenants',
      [col('id', 'int4', { isIdentity: true }), col('slug', 'uuid', { hasDefault: true })],
      { primaryKey: ['id'], uniqueColumns: new Set(['slug']) },
    )
    const pool = synthesizePkRows(parent, [{}, {}], ['slug'])
    expect(pool).toHaveLength(2)
    expect(typeof pool[0]!.slug).toBe('string')
    expect(pool[0]!.slug).not.toBe(pool[1]!.slug)
  })

  it('keeps returning plain PK rows when nothing references a non-PK column', () => {
    const t = tbl('t', [col('id', 'int4', { isIdentity: true })], { primaryKey: ['id'] })
    const pool = synthesizePkRows(t, [{}, {}], [])
    expect(pool).toEqual([{ id: 1 }, { id: 2 }])
  })
})

/* ------------------------------------------------------------------ *
 * Bug 3 — the dry-run estimate and the live meter used different prices.
 *
 * planRun hardcoded gpt-4o-mini's $0.15/$0.60 regardless of --provider, so
 * an Anthropic run was estimated at OpenAI's cheapest rate and then metered
 * at Anthropic's. On top of that the Anthropic price table was empty and
 * its fallback ($3/$15) was exactly 3x the real rate for the default model
 * (claude-haiku-4-5 at $1/$5), so --max-cost aborted runs nowhere near the
 * cap.
 * ------------------------------------------------------------------ */
describe('regression: one price table drives both cost numbers', () => {
  const anthropic = createAnthropicProvider({ apiKey: 'x', model: 'claude-haiku-4-5' })
  const openai = createOpenAiProvider({ apiKey: 'x', model: 'gpt-4o-mini' })

  it('prices the default Anthropic model at its real rate', () => {
    expect(anthropic.rates).toEqual({ inputPerMTok: 1, outputPerMTok: 5 })
  })

  it('resolves a dated model id to its family', () => {
    const dated = createAnthropicProvider({ apiKey: 'x', model: 'claude-haiku-4-5-20251001' })
    expect(dated.rates).toEqual({ inputPerMTok: 1, outputPerMTok: 5 })
  })

  it('prefers the longest matching prefix', () => {
    // 'gpt-4o-mini' must not be shadowed by 'gpt-4o' whatever the key order.
    expect(openai.rates).toEqual({ inputPerMTok: 0.15, outputPerMTok: 0.6 })
    expect(createOpenAiProvider({ apiKey: 'x', model: 'gpt-4o' }).rates).toEqual({
      inputPerMTok: 2.5,
      outputPerMTok: 10,
    })
  })

  it('falls back pessimistically for an unpriced model', () => {
    // A guardrail that under-bills is worse than one that over-bills: the
    // former overshoots --max-cost silently. Both fallbacks must be >= every
    // rate in their own table.
    const unknownAnthropic = createAnthropicProvider({ apiKey: 'x', model: 'claude-future-9' })
    const unknownOpenai = createOpenAiProvider({ apiKey: 'x', model: 'o9-preview' })
    expect(unknownAnthropic.rates.inputPerMTok).toBeGreaterThanOrEqual(10)
    expect(unknownAnthropic.rates.outputPerMTok).toBeGreaterThanOrEqual(50)
    expect(unknownOpenai.rates.inputPerMTok).toBeGreaterThanOrEqual(2.5)
    expect(unknownOpenai.rates.outputPerMTok).toBeGreaterThanOrEqual(10)
  })

  it('estimates with the selected provider rather than a hardcoded OpenAI rate', () => {
    const tables = [tbl('t', [col('a', 'text'), col('b', 'text')])]
    const opts = (provider: Provider) => ({
      rowsPerTable: 10,
      batchSize: 25,
      profile: 'saas' as const,
      provider,
      maxCostUsd: 1,
      dryRun: true,
    })

    const viaAnthropic = planRun(tables, opts(anthropic))[0]!.estimatedCostUsd
    const viaOpenai = planRun(tables, opts(openai))[0]!.estimatedCostUsd

    // 2 cols x 10 rows = 20 cells -> 1600 input + 800 output tokens.
    expect(viaAnthropic).toBeCloseTo((1600 / 1e6) * 1 + (800 / 1e6) * 5, 10)
    expect(viaOpenai).toBeCloseTo((1600 / 1e6) * 0.15 + (800 / 1e6) * 0.6, 10)
    expect(viaAnthropic).not.toBeCloseTo(viaOpenai, 10)
  })

  it('estimates zero only for the simulated provider', () => {
    const sim = createSimulatedProvider()
    expect(sim.rates).toEqual({ inputPerMTok: 0, outputPerMTok: 0 })
  })
})

/* ------------------------------------------------------------------ *
 * Bug 4 — run telemetry contradicted the published privacy promise.
 *
 * The README promises "no table or column names, no row data". The payload
 * carried every table name, the schema name, and raw error text. Postgres
 * unique-violation messages embed the offending value verbatim, so the
 * third one leaked actual customer rows.
 * ------------------------------------------------------------------ */
describe('regression: telemetry error classification leaks nothing', () => {
  it('reduces a Postgres unique violation to its SQLSTATE', () => {
    const pgErr = Object.assign(
      new Error(
        'duplicate key value violates unique constraint "users_email_key"\n' +
          'Key (email)=(ada@example.com) already exists.',
      ),
      { code: '23505' },
    )
    const cls = classifyError(pgErr)
    expect(cls).toBe('pg_23505')
    expect(cls).not.toContain('ada@example.com')
    expect(cls).not.toContain('users')
    expect(cls).not.toContain('email')
  })

  it('reduces a provider failure to its HTTP status', () => {
    expect(classifyError(new Error('Anthropic 429: rate limited'))).toBe('provider_http_429')
    expect(classifyError(new Error('OpenAI 400: {"error":{"message":"..."}}'))).toBe(
      'provider_http_400',
    )
  })

  it('recognises the failures satus raises itself', () => {
    expect(classifyError(new Error('Cost budget exceeded ($2.00 > $1)'))).toBe('budget_exceeded')
    expect(
      classifyError(new Error('No parent rows available for orders.user_id -> users.id.')),
    ).toBe('no_parent_rows')
    expect(
      classifyError(new Error('Cannot resolve orders.user_email -> users.email: ...')),
    ).toBe('fk_unresolvable')
    expect(classifyError(new Error('--truncate cannot run: ...'))).toBe('truncate_blocked')
  })

  it('returns a constant rather than a truncated message for anything unknown', () => {
    // The dangerous alternative is slicing the message: a truncated
    // Postgres error is precisely where a row value would survive.
    const leaky = new Error('some novel failure mentioning secret_table.customer_ssn')
    const cls = classifyError(leaky)
    expect(cls).toBe('unknown')
    expect(cls).not.toContain('secret_table')
    expect(cls).not.toContain('customer_ssn')
  })

  it('never emits anything outside a safe character set', () => {
    // The ingest route validates /^[a-zA-Z0-9_]+$/; a class that fails it
    // would be silently dropped as an invalid payload.
    const samples = [
      Object.assign(new Error('x'), { code: '23503' }),
      new Error('Anthropic 404:'),
      new Error('Failed to parse model JSON: Unexpected token'),
      new Error('OpenAI returned no content'),
      new Error("Anthropic returned no 'emit_rows' tool_use block (stop_reason=max_tokens)."),
      new Error('anything at all'),
      null,
      undefined,
    ]
    for (const s of samples) {
      expect(classifyError(s)).toMatch(/^[a-zA-Z0-9_]+$/)
    }
  })
})
