/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as QuickstartRouteImport } from './routes/quickstart'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CliRouteImport } from './routes/cli'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsHowItWorksRouteImport } from './routes/docs.how-it-works'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicLicenseVerifyRouteImport } from './routes/api/public/license/verify'
import { Route as ApiPublicHooksE2eHealthRouteImport } from './routes/api/public/hooks/e2e-health'
import { Route as ApiPublicCliRunRouteImport } from './routes/api/public/cli/run'
import { Route as ApiPublicBillingPortalRouteImport } from './routes/api/public/billing/portal'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickstartRoute = QuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/docs/troubleshooting',
  path: '/docs/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHowItWorksRoute = DocsHowItWorksRouteImport.update({
  id: '/docs/how-it-works',
  path: '/docs/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseVerifyRoute = ApiPublicLicenseVerifyRouteImport.update({
  id: '/api/public/license/verify',
  path: '/api/public/license/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksE2eHealthRoute = ApiPublicHooksE2eHealthRouteImport.update({
  id: '/api/public/hooks/e2e-health',
  path: '/api/public/hooks/e2e-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCliRunRoute = ApiPublicCliRunRouteImport.update({
  id: '/api/public/cli/run',
  path: '/api/public/cli/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingPortalRoute = ApiPublicBillingPortalRouteImport.update({
  id: '/api/public/billing/portal',
  path: '/api/public/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/quickstart': typeof QuickstartRoute
  '/recipes': typeof RecipesRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/cli/run': typeof ApiPublicCliRunRoute
  '/api/public/hooks/e2e-health': typeof ApiPublicHooksE2eHealthRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/quickstart': typeof QuickstartRoute
  '/recipes': typeof RecipesRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog': typeof BlogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/cli/run': typeof ApiPublicCliRunRoute
  '/api/public/hooks/e2e-health': typeof ApiPublicHooksE2eHealthRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/quickstart': typeof QuickstartRoute
  '/recipes': typeof RecipesRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog/': typeof BlogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/cli/run': typeof ApiPublicCliRunRoute
  '/api/public/hooks/e2e-health': typeof ApiPublicHooksE2eHealthRoute
  '/api/public/license/verify': typeof ApiPublicLicenseVerifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli'
    | '/compare'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/quickstart'
    | '/recipes'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/docs/how-it-works'
    | '/docs/troubleshooting'
    | '/email/unsubscribe'
    | '/blog/'
    | '/checkout/'
    | '/docs/'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/api/public/billing/portal'
    | '/api/public/cli/run'
    | '/api/public/hooks/e2e-health'
    | '/api/public/license/verify'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli'
    | '/compare'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/quickstart'
    | '/recipes'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/docs/how-it-works'
    | '/docs/troubleshooting'
    | '/email/unsubscribe'
    | '/blog'
    | '/checkout'
    | '/docs'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/api/public/billing/portal'
    | '/api/public/cli/run'
    | '/api/public/hooks/e2e-health'
    | '/api/public/license/verify'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/cli'
    | '/compare'
    | '/pricing'
    | '/privacy'
    | '/profiles'
    | '/quickstart'
    | '/recipes'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/docs/how-it-works'
    | '/docs/troubleshooting'
    | '/email/unsubscribe'
    | '/blog/'
    | '/checkout/'
    | '/docs/'
    | '/api/public/waitlist'
    | '/lovable/email/suppression'
    | '/api/public/billing/portal'
    | '/api/public/cli/run'
    | '/api/public/hooks/e2e-health'
    | '/api/public/license/verify'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliRoute: typeof CliRoute
  CompareRoute: typeof CompareRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilesRoute: typeof ProfilesRoute
  QuickstartRoute: typeof QuickstartRoute
  RecipesRoute: typeof RecipesRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DocsHowItWorksRoute: typeof DocsHowItWorksRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicBillingPortalRoute: typeof ApiPublicBillingPortalRoute
  ApiPublicCliRunRoute: typeof ApiPublicCliRunRoute
  ApiPublicHooksE2eHealthRoute: typeof ApiPublicHooksE2eHealthRoute
  ApiPublicLicenseVerifyRoute: typeof ApiPublicLicenseVerifyRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickstart': {
      id: '/quickstart'
      path: '/quickstart'
      fullPath: '/quickstart'
      preLoaderRoute: typeof QuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/docs/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/how-it-works': {
      id: '/docs/how-it-works'
      path: '/docs/how-it-works'
      fullPath: '/docs/how-it-works'
      preLoaderRoute: typeof DocsHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/verify': {
      id: '/api/public/license/verify'
      path: '/api/public/license/verify'
      fullPath: '/api/public/license/verify'
      preLoaderRoute: typeof ApiPublicLicenseVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/e2e-health': {
      id: '/api/public/hooks/e2e-health'
      path: '/api/public/hooks/e2e-health'
      fullPath: '/api/public/hooks/e2e-health'
      preLoaderRoute: typeof ApiPublicHooksE2eHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cli/run': {
      id: '/api/public/cli/run'
      path: '/api/public/cli/run'
      fullPath: '/api/public/cli/run'
      preLoaderRoute: typeof ApiPublicCliRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/portal': {
      id: '/api/public/billing/portal'
      path: '/api/public/billing/portal'
      fullPath: '/api/public/billing/portal'
      preLoaderRoute: typeof ApiPublicBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliRoute: CliRoute,
  CompareRoute: CompareRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilesRoute: ProfilesRoute,
  QuickstartRoute: QuickstartRoute,
  RecipesRoute: RecipesRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DocsHowItWorksRoute: DocsHowItWorksRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  BlogIndexRoute: BlogIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicBillingPortalRoute: ApiPublicBillingPortalRoute,
  ApiPublicCliRunRoute: ApiPublicCliRunRoute,
  ApiPublicHooksE2eHealthRoute: ApiPublicHooksE2eHealthRoute,
  ApiPublicLicenseVerifyRoute: ApiPublicLicenseVerifyRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
