
GRANT USAGE ON SCHEMA satus_demo TO PUBLIC;
GRANT ALL ON ALL TABLES IN SCHEMA satus_demo TO PUBLIC;
GRANT ALL ON ALL SEQUENCES IN SCHEMA satus_demo TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA satus_demo GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA satus_demo GRANT ALL ON SEQUENCES TO PUBLIC;
